version: '3.8'

services:
  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: short_link_visits
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
